### ISSUE TITLE
Error handling on Zope root is broken

### ISSUE THREAD

**Issue by mliebischer** [collective/collective.sentry#9]
Hi, in current release the error handling for sentry does seem broken on Zope root. I see an `plone.api.exc.CannotGetPortalError` exception when an error occurred on Zope root, e.g. /manage which would raises an Unauthorized error. This possible prevents Sentry from receiving any error which happens on Zope root and prevents me from login to ZMI.

**Steps to reproduce:**
1. Install fresh Plone 5.2.1 with collective.sentry 0.2.2
2. Clear browser cache and log out if needed.
3. Go to http://localhost:8000/manage
4. (Alternative try to produce an IPubFailure by calling any non existing or private content like http://localhost:8000/foo.bar)

**Expected result:**
Should show the ZMI of Zope root

**Actual result:**
Raises `CannotGetPortalError` from Plone API.

<details>
  <summary>Full Stacktrace:</summary>

  ```
2020-07-17 11:42:17,633 ERROR   [waitress:357][waitress] Exception while serving /manage
Traceback (most recent call last):
  File "/home/liebischer/Plone/eggs/Zope-4.1.3-py3.6.egg/ZPublisher/WSGIPublisher.py", line 156, in transaction_pubevents
    yield
  File "/home/liebischer/Plone/eggs/Zope-4.1.3-py3.6.egg/ZPublisher/WSGIPublisher.py", line 338, in publish_module
    response = _publish(request, new_mod_info)
  File "/home/liebischer/Plone/eggs/Zope-4.1.3-py3.6.egg/ZPublisher/WSGIPublisher.py", line 244, in publish
    obj = request.traverse(path, validated_hook=validate_user)
  File "/home/liebischer/Plone/eggs/Zope-4.1.3-py3.6.egg/ZPublisher/BaseRequest.py", line 649, in traverse
    response.unauthorized()
  File "/home/liebischer/Plone/eggs/Zope-4.1.3-py3.6.egg/ZPublisher/HTTPResponse.py", line 1027, in unauthorized
    raise exc
zExceptions.unauthorized.Unauthorized: You are not authorized to access this resource.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/liebischer/Plone/eggs/waitress-1.4.2-py3.6.egg/waitress/channel.py", line 349, in service
    task.service()
  File "/home/liebischer/Plone/eggs/waitress-1.4.2-py3.6.egg/waitress/task.py", line 169, in service
    self.execute()
  File "/home/liebischer/Plone/eggs/waitress-1.4.2-py3.6.egg/waitress/task.py", line 439, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "/home/liebischer/Plone/eggs/Paste-3.1.1-py3.6.egg/paste/translogger.py", line 69, in __call__
    return self.application(environ, replacement_start_response)
  File "/home/liebischer/Plone/eggs/Zope-4.1.3-py3.6.egg/ZPublisher/httpexceptions.py", line 30, in __call__
    return self.application(environ, start_response)
  File "/home/liebischer/Plone/eggs/Zope-4.1.3-py3.6.egg/ZPublisher/WSGIPublisher.py", line 343, in publish_module
    environ['REMOTE_USER'] = user.getUserName()
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/liebischer/Plone/eggs/Zope-4.1.3-py3.6.egg/ZPublisher/WSGIPublisher.py", line 210, in transaction_pubevents
    notify(pubevents.PubFailure(request, exc_info, retry))
  File "/home/liebischer/Plone/eggs/zope.event-4.4-py3.6.egg/zope/event/__init__.py", line 32, in notify
    subscriber(event)
  File "/home/liebischer/Plone/eggs/zope.component-4.5-py3.6.egg/zope/component/event.py", line 27, in dispatch
    component_subscribers(event, None)
  File "/home/liebischer/Plone/eggs/zope.component-4.5-py3.6.egg/zope/component/_api.py", line 124, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/home/liebischer/Plone/eggs/zope.interface-4.6.0-py3.6-linux-x86_64.egg/zope/interface/registry.py", line 442, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/home/liebischer/Plone/eggs/zope.interface-4.6.0-py3.6-linux-x86_64.egg/zope/interface/adapter.py", line 607, in subscribers
    subscription(*objects)
  File "/home/liebischer/Plone/eggs/collective.sentry-0.2.2-py3.6.egg/collective/sentry/error_handler.py", line 189, in errorRaisedSubscriber
    error_log = api.portal.get_tool(name="error_log")
  File "</home/liebischer/Plone/eggs/decorator-4.4.1-py3.6.egg/decorator.py:decorator-gen-2>", line 2, in get_tool
  File "/home/liebischer/Plone/eggs/plone.api-1.10.0-py3.6.egg/plone/api/validation.py", line 77, in wrapped
    return function(*args, **kwargs)
  File "/home/liebischer/Plone/eggs/plone.api-1.10.0-py3.6.egg/plone/api/portal.py", line 118, in get_tool
    return getToolByName(get(), name)
  File "/home/liebischer/Plone/eggs/plone.api-1.10.0-py3.6.egg/plone/api/portal.py", line 82, in get
    'Unable to get the portal object. More info on '
plone.api.exc.CannotGetPortalError: Unable to get the portal object. More info on http://docs.plone.org/develop/plone.api/docs/api/exceptions.html#plone.api.exc.CannotGetPortalError
```

</details>

**My troubleshooting results so far:**
The issue seems related to merge request https://github.com/collective/collective.sentry/pull/8 which introduce an new check to ignored  specific exceptions defined in `error_log` tool, but Plone API can't not determine the portal to get the correct tool from if the requested object is not within a Plone Portal. The error does not occur in collective.sentry 0.2.1.

**Possible fix:**
https://github.com/collective/collective.sentry/blob/85c85a62b90f5e341750132eff1e7dd5c5268cf8/collective/sentry/error_handler.py#L189 Get the  `error_log` tool from current portal or from zope app. For more details see `findContext()` from plone.app.theming (https://github.com/plone/plone.app.theming/blob/39dcb15feba2e70c8233c8d230efdd3eee286315/src/plone/app/theming/utils.py#L188).  If it fails to get the tool, then the ignore check for exceptions should be skipped. 

Example:
```
from Products.CMFCore.utils import getToolByName
from plone.app.theming.utils import findContext

try:
    from zope.component.hooks import getSite
except ImportError:
    from zope.app.component.hooks import getSite
..

@adapter(IPubFailure)
def errorRaisedSubscriber(event):
    
    try:
        context = findContext(event.request)
        error_log = getToolByName(context, name="error_log")
        if sys.exc_info()[0].__name__ in error_log._ignored_exceptions:
            return
    except AttributeError:
        pass

    with sentry_sdk.push_scope() as scope:
..
```

**Comment by cekk** [comment]
i can confirm this issue. I have the same error.

**Comment by zopyx** [comment]
I see  the same error within a Plone site...but no idea how to reproduce

**Comment by zopyx** [comment]
Release with 0.2.3
